version: "3.9"

services:

  mysql-node1:
    image: mysql:8.0
    container_name: mysql-node1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inventory
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl
      - MYSQL_REPLICATION_PASSWORD=replpass
    ports:
      - "3307:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mysql-node2:
    image: mysql:8.0
    container_name: mysql-node2
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"

  mysql-node3:
    image: mysql:8.0
    container_name: mysql-node3
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3309:3306"

  backend:
    build: 
      context: .
      dockerfile: devops/Dockerfile
    container_name: inventory-backend
    depends_on:
      - mysql-node1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-node1:3306/inventory
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"